package com.product.hms.exception;

import org.springframework.http.HttpStatus;

/**
 * Centralized error codes for API exception mapping.
 * Organized by domain for easy navigation and future expansion.
 *
 * @since 1.0
 */
public enum ErrorCode {
    // Generic / Common Errors
    INVALID_REQUEST("INVALID_REQUEST", HttpStatus.BAD_REQUEST),
    INVALID_DATA("INVALID_DATA", HttpStatus.BAD_REQUEST),
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND", HttpStatus.NOT_FOUND),
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR", HttpStatus.INTERNAL_SERVER_ERROR),

    // Customer Domain
    CUSTOMER_NOT_FOUND("CUSTOMER_NOT_FOUND", HttpStatus.NOT_FOUND),
    CUSTOMER_INACTIVE("CUSTOMER_INACTIVE", HttpStatus.CONFLICT),
    DUPLICATE_IDENTITY_CARD("DUPLICATE_IDENTITY_CARD", HttpStatus.CONFLICT),
    DUPLICATE_EMAIL("DUPLICATE_EMAIL", HttpStatus.CONFLICT),
    USER_NOT_FOUND("USER_NOT_FOUND", HttpStatus.NOT_FOUND),

    // Room Domain
    ROOM_NOT_FOUND("ROOM_NOT_FOUND", HttpStatus.NOT_FOUND),
    ROOM_INACTIVE("ROOM_INACTIVE", HttpStatus.CONFLICT),
    ROOM_CLASS_NOT_FOUND("ROOM_CLASS_NOT_FOUND", HttpStatus.NOT_FOUND),
    ROOM_CLASS_INACTIVE("ROOM_CLASS_INACTIVE", HttpStatus.CONFLICT),
    INSUFFICIENT_AVAILABLE_ROOMS("INSUFFICIENT_AVAILABLE_ROOMS", HttpStatus.CONFLICT),
    EXCEED_MAX_CAPACITY("EXCEED_MAX_CAPACITY", HttpStatus.BAD_REQUEST),
    ROOM_CHANGE_NOT_ALLOWED("ROOM_CHANGE_NOT_ALLOWED", HttpStatus.CONFLICT),
    ROOM_ALREADY_ASSIGNED("ROOM_ALREADY_ASSIGNED", HttpStatus.CONFLICT),
    ROOM_UPGRADE_NOT_ALLOWED("ROOM_UPGRADE_NOT_ALLOWED", HttpStatus.CONFLICT),
    NOTE_REQUIRED("NOTE_REQUIRED", HttpStatus.BAD_REQUEST),

    // Staff Domain
    STAFF_NOT_FOUND("STAFF_NOT_FOUND", HttpStatus.NOT_FOUND),

    // Shift Domain
    SHIFT_NOT_FOUND("SHIFT_NOT_FOUND", HttpStatus.NOT_FOUND),

    // Reservation Domain
    RESERVATION_NOT_FOUND("RESERVATION_NOT_FOUND", HttpStatus.NOT_FOUND),
    INVALID_DATE_RANGE("INVALID_DATE_RANGE", HttpStatus.BAD_REQUEST),
    RESERVATION_UPDATE_LOCKED("RESERVATION_UPDATE_LOCKED", HttpStatus.CONFLICT),
    RESERVATION_ALREADY_CANCELED("RESERVATION_ALREADY_CANCELED", HttpStatus.CONFLICT),
    RESERVATION_CANCEL_NOT_ALLOWED("RESERVATION_CANCEL_NOT_ALLOWED", HttpStatus.CONFLICT),
    RESERVATION_CHECKIN_NOT_ALLOWED("RESERVATION_CHECKIN_NOT_ALLOWED", HttpStatus.CONFLICT),
    RESERVATION_CHECKOUT_NOT_ALLOWED("RESERVATION_CHECKOUT_NOT_ALLOWED", HttpStatus.CONFLICT),
    RESERVATION_ROOM_HAS_PENDING_SERVICES("RESERVATION_ROOM_HAS_PENDING_SERVICES", HttpStatus.CONFLICT),
    RESERVATION_ROOM_NOT_CHECKED_IN("RESERVATION_ROOM_NOT_CHECKED_IN", HttpStatus.CONFLICT),
    RESERVATION_ROOM_ASSIGNMENT_REQUIRED("RESERVATION_ROOM_ASSIGNMENT_REQUIRED", HttpStatus.BAD_REQUEST),
    ROOM_NOT_AVAILABLE("ROOM_NOT_AVAILABLE", HttpStatus.CONFLICT),
    ROOM_CLASS_MISMATCH("ROOM_CLASS_MISMATCH", HttpStatus.BAD_REQUEST),

    // Service Domain
    SERVICE_NOT_FOUND("SERVICE_NOT_FOUND", HttpStatus.NOT_FOUND),
    SERVICE_INACTIVE("SERVICE_INACTIVE", HttpStatus.CONFLICT),
    SERVICE_BOOKING_NOT_FOUND("SERVICE_BOOKING_NOT_FOUND", HttpStatus.NOT_FOUND),
    SERVICE_BOOKING_NOT_ALLOWED("SERVICE_BOOKING_NOT_ALLOWED", HttpStatus.CONFLICT),
    RESERVATION_ROOM_NOT_FOUND("RESERVATION_ROOM_NOT_FOUND", HttpStatus.NOT_FOUND),

    // Folio & Payment Domain
    FOLIO_ALREADY_CLOSED("FOLIO_ALREADY_CLOSED", HttpStatus.CONFLICT),
    INSUFFICIENT_PAYMENT("INSUFFICIENT_PAYMENT", HttpStatus.BAD_REQUEST),
    INSUFFICIENT_DEPOSIT("INSUFFICIENT_DEPOSIT", HttpStatus.BAD_REQUEST),
    PAYMENT_NOT_FOUND("PAYMENT_NOT_FOUND", HttpStatus.NOT_FOUND),

    // Task & Housekeeping Domain
    TASK_NOT_FOUND("TASK_NOT_FOUND", HttpStatus.NOT_FOUND),

    // Utilities / Technical Errors
    INVALID_PAGE_PARAMS("INVALID_PAGE_PARAMS", HttpStatus.BAD_REQUEST),
    PAGE_NOT_FOUND("PAGE_NOT_FOUND", HttpStatus.NOT_FOUND),
    RESOURCE_UNSUPPORTED("RESOURCE_UNSUPPORTED", HttpStatus.BAD_REQUEST),
    MAPPING_ERROR("MAPPING_ERROR", HttpStatus.INTERNAL_SERVER_ERROR);

    private final String code;
    private final HttpStatus status;

    ErrorCode(String code, HttpStatus status) {
        this.code = code;
        this.status = status;
    }

    /**
     * Returns the error code string.
     */
    public String code() {
        return code;
    }

    /**
     * Returns the HTTP status associated with this error code.
     */
    public HttpStatus status() {
        return status;
    }
}
